import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import ReactQueryProvider from "@/utils/queryProvider";

const robotoInit = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoInit.variable} antialiased`}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
